version: '3.1'

services:
  gui:
    build: ./gui-service
    ports:
      - "5000:5000"
    depends_on:
      - patient-management
      - medical-records
      - appointment-scheduler

  patient-management:
    build: ./patient-management-service
    ports:
      - "5001:5000"
    environment:
      MONGO_URI: "mongodb://sumedhars:srsanjeev@mongo:27017/healthcare"
    depends_on:
      - mongo

  medical-records:
    build: ./medical-records-service
    ports:
      - "5002:5000"
    environment:
      MONGO_URI: "mongodb://sumedhars:srsanjeev@mongo:27017/healthcare"
    depends_on:
      - mongo

  appointment-scheduler:
    build: ./appointment-scheduler-service
    ports:
      - "5003:5000"
    environment:
      MONGO_URI: "mongodb://sumedhars:srsanjeev@mongo:27017/healthcare"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sumedhars
      MONGO_INITDB_ROOT_PASSWORD: srsanjeev
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sumedhars
      ME_CONFIG_MONGODB_ADMINPASSWORD: srsanjeev
      ME_CONFIG_MONGODB_URL: "mongodb://sumedhars:srsanjeev@mongo:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpass
    depends_on:
      - mongo

volumes:
  mongo-data:
